runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /assets/css
    static_dir: assets/css

  - url: /assets/fonts
    static_dir: assets/fonts

  - url: /assets/css/theme-color
    static_dir: assets/css/theme-color

  - url: /assets/js
    static_dir: assets/js

  - url: /assets/images
    static_dir: assets/images

  # - url: /images
  #   static_dir: pictures

  - url: .*
    script: main.app

libraries:
  - name: jinja2
    version: latest
  - name: webapp2
    version: "2.5.2"
